name: 'WebApp Deploy Action'
description: 'An action that deploys a web application artifact.'

inputs:
  environment:
    description: 'The target environment for deployment (e.g., staging, production).'
    required: true
  artifactName:
    description: 'The name of the artifact to deploy.'
    required: true
  deployPath:
    description: 'The path where the artifact will be deployed.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: 'webapp-build-artifact'
        path: './artifact'

    - name: Unzip Artifact
      run: unzip ${{ github.workspace }}/artifact/*.zip -d ${{ github.workspace }}/unzipped
      shell: bash

    - name: Deploy Artifact
      run: |
        echo "Deploying to environment: ${{ inputs.environment }}"
        echo "Artifact: ${{ inputs.artifactName }}"
        echo "Deploying to path: ${{ inputs.deployPath }}"
        echo "Deployment complete."
      shell: bash
