name: Test-Main

on:
  workflow_dispatch:
    inputs:
      artifactName:
        description: 'Name of the artifact'
        required: true
        type: string
      deployToInt:
        description: 'Deploy to Int'
        required: true
        type: boolean
        default: true
      deployToTest:
        description: 'Deploy to Test'
        required: true
        type: boolean
        default: true
      deployToTest01:
        description: 'Deploy to Test01'
        required: true
        type: boolean
        default: true
      deployToTest02:
        description: 'Deploy to Test02'
        required: true
        type: boolean
        default: true
      deployToAutomation:
        description: 'Deploy to Automation'
        required: true
        type: boolean
        default: true

jobs:
  run-webapi-action:
    uses: ./.github/actions/test/webapi/action.yml
    with:
      artifactName: ${{ inputs.artifactName }}
      deployToInt: ${{ inputs.deployToInt }}
      deployToTest: ${{ inputs.deployToTest }}
      deployToTest01: ${{ inputs.deployToTest01 }}
      deployToTest02: ${{ inputs.deployToTest02 }}
      deployToAutomation: ${{ inputs.deployToAutomation }}

